### ISSUE TITLE
Implement BFS(Breadth First Search) Algorithm

### ISSUE THREAD

**Issue by abarya** [abhishekarya286/practice-code#4]
Implementation of [BFS Algorithm](https://en.wikipedia.org/wiki/Breadth-first_search) for finding shortest path in a graph in C++.
Input : Source Node and Graph
Output : Print distance of all the nodes from the source node.

**Comment by anubhakushwaha** [comment]
@abhishekarya286  can I claim this?

**Comment by abarya** [comment]
Sure.
